baseURL = 'https://tarbolin69.github.io/listado-de-vendedores.github.io/'
languageCode = 'es'
title = 'Listado de Vendedores - La Costa'
theme="archie"
copyright= "© Sol Caronte"
googleAnalytics = 'G-1YH6NXG8CR'
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="auto"
	useCDN=false
[[params.social]]
name = "Municipalidad"
icon = "briefcase"
url = "https://lacosta.gob.ar/"

[[params.social]]
name = "Contacto"
icon = "mail"
url = "mailto:nicolas@solcaronte.xyz"

[[menu.main]]
name = "Localidades"
url = "/tags"
weight = 2

[[menu.main]]
name = "Negocios"
url = "/tags/negocio"
weight = 3

[[menu.main]]
name = "Municipalidad"
url = "https://lacosta.gob.ar/"
weight = 4
